<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjaitmo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjaitmo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWjaitmo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWjaitmo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWjaitmo\appDevDebugProjectContainer([
    'container.build_hash' => 'Wjaitmo',
    'container.build_id' => '14ee4fae',
    'container.build_time' => 1582576888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjaitmo');
