<?php

namespace activiteBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findReponseByQuestionId($id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('activiteBundle:Reponse', 'p')
            ->where('p.question = :qu')
                ->setParameter('qu', $id )

            ->getQuery();
        return $q->getResult();
    }
}
