<?php

namespace activiteBundle\Repository;

/**
 * ReponseEleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseEleveRepository extends \Doctrine\ORM\EntityRepository
{
}
