<?php

namespace BibliothequeBundle\Repository;

/**
 * LivreRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
