<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'activite.Reponse' shared service.

return $this->services['activite.Reponse'] = new \activiteBundle\Controller\ReponseController($this);
