<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knp_snappy.pdf' shared service.

$this->services['knp_snappy.pdf'] = $instance = new \Knp\Snappy\Pdf('C://wkhtmltopdf/bin/wkhtmltopdf.exe', [], []);

$instance->setLogger(${($_ = isset($this->services['monolog.logger.snappy']) ? $this->services['monolog.logger.snappy'] : $this->load('getMonolog_Logger_SnappyService.php')) && false ?: '_'});
$instance->setTemporaryFolder(($this->targetDirs[3].'/web/uploads/images/'));
$instance->setTimeout(20);

return $instance;
