user_livre:
    resource: "@BibliothequeBundle/Resources/config/routing/livre.yml"
    prefix:   /livre
user_categorie:
    resource: "@BibliothequeBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie
user_reservation:
    resource: "@BibliothequeBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation