<?php

namespace activiteBundle\Repository;

/**
 * ProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfRepository extends \Doctrine\ORM\EntityRepository
{
}
